site_name: NdFeB KB
docs_dir: docs
site_url: https://ndfeb.fr/kb
repo_url: https://github.com/NeodymiumFerBore/wiki-pages
edit_uri: edit/master/docs/
theme:
  name: material
  font: false # disable loading fonts from google for data privacy reason
  icon:
    repo: fontawesome/brands/github-alt
  palette:
    - scheme: slate
      primary: indigo
      accent: ingido
  features:
    - navigation.tabs
    - navigation.tabs.sticky # Insiders only, but maybe one day...
copyright: |
  <div style="display:inline-flex; flex-direction:row; gap:5px; align-items:center;">
    <div>
    <a href=https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en>
      <img src="https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by-nc-sa.svg" alt="CC Attribution-Noncommercial-Share Alike 4.0 International License" align="center">
    </a>
    </div>
    <div>
      <p style="font-size:.56rem; color:var(--md-footer-fg-color--lighter);">
        Except where otherwise noted, content on this wiki <br> is licensed under
        <a href=https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en style="color:var(--md-footer-fg-color--light);" target="_blank" rel="noreferrer noopener">
          CC-BY-NC-SA 4.0 License
        </a>
      </p>
    </div>
  </div>
extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/users/NdFeB/projects
    - icon: fontawesome/brands/github
      link: https://github.com/NeodymiumFerBore

  # Define where assets are stored. {{ assets.path }} will then be used
  assets:
    path: https://ndfeb.fr/kb/files

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - awesome-pages
  - git-revision-date
  - macros # show predefined variables: {{ macros_info() }}

# https://squidfunk.github.io/mkdocs-material/reference/admonitions/
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - admonition              # Block "note" blocks
  - pymdownx.details        # For spoiler blocks, integrates with admonition
  - pymdownx.keys           # For key images with ++ctrl+c++

# Use awesome-pages for nav, and define .pages in subfolders
