site_name: NdFeB Wiki
docs_dir: docs
site_url: https://ndfeb.fr/wiki
repo_url: https://github.com/NeodymiumFerBore/wiki-pages
edit_uri: edit/master/docs/
theme:
  name: material
  font: false # disable loading fonts from google for data privacy reason
  icon:
    repo: fontawesome/brands/github-alt
  palette:
    - scheme: slate
      primary: indigo
      accent: ingido
  features:
    - navigation.tabs
    - navigation.tabs.sticky # Insiders only, but maybe one day...
extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/users/NdFeB/projects
    - icon: fontawesome/brands/github
      link: https://github.com/NeodymiumFerBore

  # Define where assets are stored. {{ assets.path }} will then be used
  assets:
    path: https://ndfeb.fr/wiki/files

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - awesome-pages
  - git-revision-date
  - macros # show predefined variables: {{ macros_info() }}

# https://squidfunk.github.io/mkdocs-material/reference/admonitions/
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - admonition              # Block "note" blocks
  - pymdownx.details        # For spoiler blocks, integrates with admonition
  - pymdownx.keys           # For key images with ++ctrl+c++

# Use awesome-pages for nav, and define .pages in subfolders
